apiVersion : apps/v1
kind: Deployment
metadata:
  name: "customer12-6116"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "customer12-6116"
  template:
    metadata:
      labels:
        app: "customer12-6116"
    spec:
      containers:
        - name: "customer12-6116"
          image: "customer123.azurecr.io/customer12"
          ports:
          - containerPort: 80