apiVersion: v1
kind: Service
metadata:
    name: "customer12-6116"
    labels:
        app: "customer12-6116"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "customer12-6116"