on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: rulecr.azurecr.io
        username: ${{ secrets.acr_rulecr_username }}
        password: ${{ secrets.acr_rulecr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t rulecr.azurecr.io/ruleaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push rulecr.azurecr.io/ruleaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_ruleaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ruleaksb5f2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ruleaksb5f2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ruleaksb5f2
        container-registry-url: rulecr.azurecr.io
        container-registry-username: ${{ secrets.acr_rulecr_username }}
        container-registry-password: ${{ secrets.acr_rulecr_password }}
        secret-name: ruleaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ruleaksb5f2
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          rulecr.azurecr.io/ruleaks:${{ github.sha }}
        imagepullsecrets: |
          ruleaksdockerauth
